title: "Моё портфолио"
description: "Важность портфолио для программиста и мой опыт."
baseurl: ""  # For GitHub Pages, this should remain empty unless you're using a custom domain
url: "https://ramazsafin.github.io/"  # Your GitHub Pages URL
theme:

# Navigation links
nav:
  - title: "Главная"
    url: /
  - title: "Обо мне"
    url: /about/
  - title: "Портфолио"
    url: /portfolio/

# Author details and social links
author:
  name: "Рамаз"
  email: "safinramaz@mail.ru"
  social:
    github: "https://github.com/RamazSafin"
